/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Avell 1511' at '12/28/16 4:47 PM' with Gradle 2.14.1
 *
 * @author Avell 1511, @date 12/28/16 4:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
